repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
  - repo: https://github.com/kynan/nbstripout
    rev: master
    hooks:
      - id: nbstripout
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        name: Run pylint
        entry: pylint --rcfile=pyproject.toml
        args: [src/topotoolbox/]
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: Run type checks
        entry: mypy --ignore-missing-imports
        args: [src/topotoolbox/]
        types: [python]
